// Builds supabase/seed.sql from seed-data/sessions.csv.
// Usage: node scripts/build-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";

const CSV_PATH = new URL("../seed-data/sessions.csv", import.meta.url);
const SEED_PATH = new URL("../supabase/seed.sql", import.meta.url);
const HEADER = "date,day,room";
const DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

// Parses and validates every row; throws on the first bad line so a typo can't reach the DB.
function parseRows(csv) {
  const [header, ...lines] = csv.trim().split(/\r?\n/);

  if (header !== HEADER) {
    throw new Error(`Expected header "${HEADER}", got "${header}"`);
  }

  const seen = new Set();

  return lines.map((line, i) => {
    const lineNo = i + 2;
    const fields = line.split(",");

    if (fields.length !== 3) {
      throw new Error(`Line ${lineNo}: expected 3 fields, got ${fields.length}`);
    }

    const [date, day, room] = fields.map((f) => f.trim());

    if (!ISO_DATE.test(date)) {
      throw new Error(`Line ${lineNo}: bad date "${date}"`);
    }

    // The CSV's day column must agree with the calendar, e.g. 2026-10-05 is a Monday.
    const actualDay = DAY_NAMES[new Date(`${date}T00:00:00Z`).getUTCDay()];

    if (actualDay !== day) {
      throw new Error(`Line ${lineNo}: ${date} is a ${actualDay}, not ${day}`);
    }

    if (!room) {
      throw new Error(`Line ${lineNo}: empty room`);
    }

    const key = `${date}|${room}`;

    if (seen.has(key)) {
      throw new Error(`Line ${lineNo}: duplicate ${room} on ${date}`);
    }

    seen.add(key);
    return { date, room };
  });
}

// SQL string literal with quotes escaped.
function sqlText(value) {
  return `'${value.replaceAll("'", "''")}'`;
}

// Each room's position is where it first appears in the CSV, so the CSV's order is the display order.
function roomPositions(rows) {
  const positions = new Map();

  for (const { room } of rows) {
    if (!positions.has(room)) {
      positions.set(room, positions.size);
    }
  }

  return positions;
}

// Re-runnable: existing rows only get their room position refreshed.
function buildSeed(rows) {
  const positions = roomPositions(rows);
  const values = rows
    .map((r) => `  (${sqlText(r.date)}, ${sqlText(r.room)}, ${positions.get(r.room)})`)
    .join(",\n");

  return [
    "-- Generated by scripts/build-seed.mjs from seed-data/sessions.csv. Do not edit by hand.",
    "insert into public.sessions (session_date, room, room_position) values",
    values,
    "on conflict (session_date, room) do update set room_position = excluded.room_position;",
    "",
  ].join("\n");
}

const rows = parseRows(readFileSync(CSV_PATH, "utf8"));
writeFileSync(SEED_PATH, buildSeed(rows));
console.log(`Wrote ${rows.length} sessions to supabase/seed.sql`);
